import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import AdicionarAluno from '@/pages/components/AdicionarAluno';
import MediaDisciplinas from '@/pages/components/MediasDisciplinas';
import MediaGeral from '@/pages/components/MediaGeral';
import AtencaoEspecial from '@/pages/components/AtencaoEspecial';
import ListarAlunos from '@/pages/components/ListarAlunos';
import LimparListaAlunos from '@/pages/components/LimparListaAlunos';



const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Gestão De Alunos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <AdicionarAluno />
        <MediaDisciplinas />
        <ListarAlunos/>
        <MediaGeral />
        <AtencaoEspecial/>
        <LimparListaAlunos/>
      </main>
    </>
  );
}
